### ISSUE TITLE
Can't minify your source 

### ISSUE THREAD

**Issue by riderx** [api-ai/apiai-javascript-client#57]
```
[15:21:42] Starting 'minify-js'...

events.js:160
      throw er; // Unhandled 'error' event
      ^
GulpUglifyError: unable to minify JavaScript
  at createError (/home/circleci/tucana/node_modules/gulp-uglify/lib/create-error.js:6:14)
  at apply (/home/circleci/tucana/node_modules/gulp-uglify/node_modules/lodash/_apply.js:16:25)
  at wrapper (/home/circleci/tucana/node_modules/gulp-uglify/node_modules/lodash/_createCurry.js:41:12)
  at /home/circleci/tucana/node_modules/gulp-uglify/lib/minify.js:54:15
  at DestroyableTransform._transform (/home/circleci/tucana/node_modules/gulp-uglify/composer.js:10:23)
  at DestroyableTransform.Transform._read (/home/circleci/tucana/node_modules/gulp-uglify/node_modules/readable-stream/lib/_stream_transform.js:182:10)
  at DestroyableTransform.Transform._write (/home/circleci/tucana/node_modules/gulp-uglify/node_modules/readable-stream/lib/_stream_transform.js:170:83)
  at doWrite (/home/circleci/tucana/node_modules/gulp-uglify/node_modules/readable-stream/lib/_stream_writable.js:406:64)
  at writeOrBuffer (/home/circleci/tucana/node_modules/gulp-uglify/node_modules/readable-stream/lib/_stream_writable.js:395:5)
  at DestroyableTransform.Writable.write (/home/circleci/tucana/node_modules/gulp-uglify/node_modules/readable-stream/lib/_stream_writable.js:322:11)
  at write (/home/circleci/tucana/node_modules/readable-stream/lib/_stream_readable.js:623:24)
  at flow (/home/circleci/tucana/node_modules/readable-stream/lib/_stream_readable.js:632:7)
  at Transform.pipeOnReadable (/home/circleci/tucana/node_modules/readable-stream/lib/_stream_readable.js:664:5)
  at emitNone (events.js:86:13)
  at Transform.emit (events.js:185:7)
  at emitReadable_ (/home/circleci/tucana/node_modules/readable-stream/lib/_stream_readable.js:448:10)
  at emitReadable (/home/circleci/tucana/node_modules/readable-stream/lib/_stream_readable.js:444:5)
  at readableAddChunk (/home/circleci/tucana/node_modules/readable-stream/lib/_stream_readable.js:187:9)
  at Transform.Readable.push (/home/circleci/tucana/node_modules/readable-stream/lib/_stream_readable.js:149:10)
  at Transform.push (/home/circleci/tucana/node_modules/readable-stream/lib/_stream_transform.js:145:32)
  at Transform._transform (/home/circleci/tucana/node_modules/gulp-ng-annotate/index.js:84:10)
  at Transform._read (/home/circleci/tucana/node_modules/readable-stream/lib/_stream_transform.js:184:10)
  at Transform._write (/home/circleci/tucana/node_modules/readable-stream/lib/_stream_transform.js:172:12)
  at doWrite (/home/circleci/tucana/node_modules/readable-stream/lib/_stream_writable.js:237:10)
  at writeOrBuffer (/home/circleci/tucana/node_modules/readable-stream/lib/_stream_writable.js:227:5)
  at Transform.Writable.write (/home/circleci/tucana/node_modules/readable-stream/lib/_stream_writable.js:194:11)
  at DestroyableTransform.ondata (/home/circleci/tucana/node_modules/gulp-ignore/node_modules/readable-stream/lib/_stream_readable.js:612:20)
  at emitOne (events.js:96:13)
  at DestroyableTransform.emit (events.js:188:7)
  at addChunk (/home/circleci/tucana/node_modules/gulp-ignore/node_modules/readable-stream/lib/_stream_readable.js:284:12)
  at readableAddChunk (/home/circleci/tucana/node_modules/gulp-ignore/node_modules/readable-stream/lib/_stream_readable.js:271:11)
  at DestroyableTransform.Readable.push (/home/circleci/tucana/node_modules/gulp-ignore/node_modules/readable-stream/lib/_stream_readable.js:238:10)
  at DestroyableTransform.Transform.push (/home/circleci/tucana/node_modules/gulp-ignore/node_modules/readable-stream/lib/_stream_transform.js:146:32)
  at DestroyableTransform._transform (/home/circleci/tucana/node_modules/gulp-ignore/index.js:18:9)
  at DestroyableTransform.Transform._read (/home/circleci/tucana/node_modules/gulp-ignore/node_modules/readable-stream/lib/_stream_transform.js:182:10)
  at DestroyableTransform.Transform._write (/home/circleci/tucana/node_modules/gulp-ignore/node_modules/readable-stream/lib/_stream_transform.js:170:83)
  at doWrite (/home/circleci/tucana/node_modules/gulp-ignore/node_modules/readable-stream/lib/_stream_writable.js:406:64)
  at writeOrBuffer (/home/circleci/tucana/node_modules/gulp-ignore/node_modules/readable-stream/lib/_stream_writable.js:395:5)
  at DestroyableTransform.Writable.write (/home/circleci/tucana/node_modules/gulp-ignore/node_modules/readable-stream/lib/_stream_writable.js:322:11)
  at write (/home/circleci/tucana/node_modules/readable-stream/lib/_stream_readable.js:623:24)
  at flow (/home/circleci/tucana/node_modules/readable-stream/lib/_stream_readable.js:632:7)
  at DestroyableTransform.pipeOnReadable (/home/circleci/tucana/node_modules/readable-stream/lib/_stream_readable.js:664:5)
  at emitNone (events.js:86:13)
  at DestroyableTransform.emit (events.js:185:7)
  at emitReadable_ (/home/circleci/tucana/node_modules/readable-stream/lib/_stream_readable.js:448:10)
  at emitReadable (/home/circleci/tucana/node_modules/readable-stream/lib/_stream_readable.js:444:5)
  at readableAddChunk (/home/circleci/tucana/node_modules/readable-stream/lib/_stream_readable.js:187:9)
  at DestroyableTransform.Readable.push (/home/circleci/tucana/node_modules/readable-stream/lib/_stream_readable.js:149:10)
  at DestroyableTransform.Transform.push (/home/circleci/tucana/node_modules/readable-stream/lib/_stream_transform.js:145:32)
  at afterTransform (/home/circleci/tucana/node_modules/readable-stream/lib/_stream_transform.js:101:12)
  at TransformState.afterTransform (/home/circleci/tucana/node_modules/readable-stream/lib/_stream_transform.js:79:12)
  at DestroyableTransform.noop [as _transform] (/home/circleci/tucana/node_modules/through2/through2.js:26:3)
  at DestroyableTransform.Transform._read (/home/circleci/tucana/node_modules/readable-stream/lib/_stream_transform.js:184:10)
  at DestroyableTransform.Transform._write (/home/circleci/tucana/node_modules/readable-stream/lib/_stream_transform.js:172:12)
  at doWrite (/home/circleci/tucana/node_modules/readable-stream/lib/_stream_writable.js:237:10)
  at writeOrBuffer (/home/circleci/tucana/node_modules/readable-stream/lib/_stream_writable.js:227:5)
  at DestroyableTransform.Writable.write (/home/circleci/tucana/node_modules/readable-stream/lib/_stream_writable.js:194:11)
  at write (/home/circleci/tucana/node_modules/readable-stream/lib/_stream_readable.js:623:24)
  at flow (/home/circleci/tucana/node_modules/readable-stream/lib/_stream_readable.js:632:7)
  at DestroyableTransform.pipeOnReadable (/home/circleci/tucana/node_modules/readable-stream/lib/_stream_readable.js:664:5)
  at emitNone (events.js:86:13)
  at DestroyableTransform.emit (events.js:185:7)
  at emitReadable_ (/home/circleci/tucana/node_modules/readable-stream/lib/_stream_readable.js:448:10)
  at emitReadable (/home/circleci/tucana/node_modules/readable-stream/lib/_stream_readable.js:444:5)
  at readableAddChunk (/home/circleci/tucana/node_modules/readable-stream/lib/_stream_readable.js:187:9)
  at DestroyableTransform.Readable.push (/home/circleci/tucana/node_modules/readable-stream/lib/_stream_readable.js:149:10)
  at DestroyableTransform.Transform.push (/home/circleci/tucana/node_modules/readable-stream/lib/_stream_transform.js:145:32)
  at afterTransform (/home/circleci/tucana/node_modules/readable-stream/lib/_stream_transform.js:101:12)
  at TransformState.afterTransform (/home/circleci/tucana/node_modules/readable-stream/lib/_stream_transform.js:79:12)
  at /home/circleci/tucana/node_modules/gulp/node_modules/vinyl-fs/lib/src/getContents/bufferFile.js:12:5
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:446:3)

error Command failed with exit code 1.
```
Our full minification work and if i do 
`ApiAi = require 'api-ai-javascript'` that break straight our build
also same problem with `import {ApiAiClient} from "api-ai-javascript"`
as you can see we use gulp minify and gulp uglify to do that.
We have many differents libs include in our project i don't get why your's break everything

**Comment by tlenclos** [comment]
This is because the source are either in typescript or ES6 and `minify-js` can't understand this. This issue is also explained here on the [`react-create-app` README](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify).
